version: "3"
services:
  memcached:
    image: memcached:1.5-alpine

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data

  convertit:
    image: makinacorpus/convertit:latest

  screamshotter:
    image: juank/screenshotter:latest

  celery:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./var:/opt/geotrek-admin/var
    depends_on:
      - memcached
      - redis
    user: ${UID:-0}:${GID:-0}
    command: celery -A geotrek worker -c 1

  web:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8001}:8000"
    volumes:
      - ./var:/opt/geotrek-admin/var
    depends_on:
      - memcached
      - redis
      - screamshotter
      - convertit
    user: ${UID:-0}:${GID:-0}

  api:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${API_PORT:-8002}:8000"
    volumes:
      - ./var:/opt/geotrek-admin/var
    depends_on:
      - memcached
      - redis
    user: ${UID:-0}:${GID:-0}

volumes:
  postgres:
  redis:
