version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  codestyle:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - run: apt update
      - run: apt install -y python3-pip
      - checkout
      - run: pip3 install flake8
      - run: flake8 --exclude "" --ignore=E501,F403,F405 geotrek/settings
      - run: flake8 geotrek
      - run: test $(ls geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID | wc -l) -eq 0
  test:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - run: apt update
      - run: DEBIAN_FRONTEND="noninteractive" apt install -y curl git sudo tzdata
      - checkout
      - run: ./install.sh --tests --noinput
      - run: sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf; service redis-server start
      - run: ./bin/coverage run ./bin/django test -v2 geotrek
      - run: apt install -y npm
      - run: make test_js
      - run: ./bin/coverage report -m && ./bin/coverage xml
      - codecov/upload:
          file: coverage.xml
          flags: test
  test_xenial:
    docker:
      - image: ubuntu:xenial
    environment:
      LANG: C.UTF-8
    steps:
      - run: apt update
      - run: DEBIAN_FRONTEND="noninteractive" apt install -y curl git sudo tzdata
      - checkout
      - run: ./install.sh --tests --noinput
      - run: sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf; service redis-server start
      - run: ./bin/django test -v2 geotrek
      - run: apt install -y npm
      - run: make test_js
  test_nds:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - run: apt update
      - run: DEBIAN_FRONTEND="noninteractive" apt install -y curl git sudo tzdata
      - checkout
      - run: sed -i 's/TREKKING_TOPOLOGY_ENABLED = True/TREKKING_TOPOLOGY_ENABLED = False/g' geotrek/settings/base.py
      - run: ./install.sh --tests --noinput
      - run: sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf; service redis-server start
      - run: ./bin/coverage run ./bin/django test -v2 geotrek --settings=geotrek.settings.tests_nds
      - run: apt install -y npm
      - run: make test_js
      - run: ./bin/coverage report -m && ./bin/coverage xml
      - codecov/upload:
          file: coverage.xml
          flags: test_nds
  deploy:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - run: chmod 755 /root  # Allow nginx to access static and media
      - run: apt update
      - run: DEBIAN_FRONTEND="noninteractive" apt install -y git sudo tzdata
      - checkout
      - run: ./install.sh --noinput
      - run: sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf; service redis-server start
      - run: make load_demo
      - run: make test_nav host=localhost port=80
workflows:
  version: 2
  all:
    jobs:
      - codestyle
      - test
      - test_nds
      - test_xenial
      - deploy
